name: Build
on: push
jobs:
  build:
    name: Build & Test
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: echo "step 1 was run"
      - name: Step 2
        run: echo "step 2 was run"
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: test-files
          path: /src/testing.txt 