name: Deploy
on: 
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit Hash'
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Deploy step 1
        run: echo "deploy step 1 run"
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: test-files
          path: tfs
          commit: ${{ github.events.inputs.commit }}
                 