name: Deploy
on: 
  push:
    branches-ignore:
      - '**'   
    tags:
      - * 
jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Deploy step 1
        run: echo "deploy step 1 run"   
      - name: Create file
        run: echo ${{ github.sha }} > deploy.txt
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: deploy-test-files
          path: deploy.txt 
                 